//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerializationHelperTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SerializationHelperTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread'txt CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ArrayOfKeyValueOfintdateTime xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfintdateTime&gt;
        ///    &lt;Key&gt;-1&lt;/Key&gt;
        ///    &lt;Value&gt;0001-01-01T00:00:00&lt;/Value&gt;
        ///  &lt;/KeyValueOfintdateTime&gt;
        ///  &lt;KeyValueOfintdateTime&gt;
        ///    &lt;Key&gt;0&lt;/Key&gt;
        ///    &lt;Value&gt;2015-05-18T21:56:32.3637023-04:00&lt;/Value&gt;
        ///  &lt;/KeyValueOfintdateTime&gt;
        ///  &lt;KeyValueOfintdateTime&gt;
        ///    &lt;Key&gt;1&lt;/Key&gt;
        ///    &lt;Value&gt;9999-12-31T23:59:59.9999999&lt;/Value&gt;
        ///  &lt;/KeyValueOfintdateTime&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DictionaryIntDateTimeXml {
            get {
                return ResourceManager.GetString("DictionaryIntDateTimeXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ArrayOfKeyValueOfanyTypeanyType xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfanyTypeanyType&gt;
        ///    &lt;Key xmlns:d3p1=&quot;http://www.w3.org/2001/XMLSchema&quot; i:type=&quot;d3p1:string&quot;&gt;second&lt;/Key&gt;
        ///    &lt;Value xmlns:d3p1=&quot;http://www.w3.org/2001/XMLSchema&quot; i:type=&quot;d3p1:int&quot;&gt;2&lt;/Value&gt;
        ///  &lt;/KeyValueOfanyTypeanyType&gt;
        ///  &lt;KeyValueOfanyTypeanyType&gt;
        ///    &lt;Key xmlns:d3p1=&quot;http://www.w3.org/2001/XMLSche [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HashTableXml {
            get {
                return ResourceManager.GetString("HashTableXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;anyType i:nil=&quot;true&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/&quot; /&gt;.
        /// </summary>
        internal static string NullObjectXml {
            get {
                return ResourceManager.GetString("NullObjectXml", resourceCulture);
            }
        }
    }
}
